version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bd_usuarios
    ports:
      - 5433:5432

volumes:
  db_data: