version: "3.7"

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bd_usuarios
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql:rw
      - ./database:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --local-infile=1
    ports:
      - 3307:3306

volumes:
  db_data: